#+TITLE: COMP-348
#+AUTHOR: Philip Dumaresq
#+SETUPFILE: templates/html.org
#+HTML_HEAD: <style>.header { display: none; }</style>
#+OPTIONS: toc:nil

#+INCLUDE: header.org

** COMMENT Java
This section is for all questions relating to Java, in particular the ~stream~ API.

** Prolog

This section is for all questions relating to Prolog.

Before getting started with Prolog, you should [[file:prolog-ide-compiler.org][set up your development environment]]. 

- [[file:prolog-debugging.org][Debugging in Prolog]]

** Lisp

This section is for all questions relating to Common Lisp.

Before getting started with Lisp, you should [[file:lisp-ide-compiler.org][set up your development environment]]. 

For a guide on the things you'll need to know about Lisp for this course, you can read [[file:lisp-tutorial.org][this tutorial]]
and it should cover most of this course, without showing you how to do things the wrong way.

For any other questions you might have, you can check out the questions I've received below.

- [[file:lisp-setting-variables.org][How to declare and set variables in Lisp]]
- [[file:lisp-quote-vs-'.org][The difference between ~quote~ and ~'~]]
- [[file:lisp-let-scoping.org][Variable scoping and ~let~ bindings]]
- [[file:lisp-running-from-terminal.org][Running Lisp from any terminal]]
- [[file:lisp-debugging.org][Debugging Common Lisp from the terminal]]
- [[file:lisp-function-definitions.org][Different ways to define functions]]
- [[file:lisp-namespaces.org][~list~ vs ~(list)~ - namespaces in Lisp]]
- [[file:lisp-cons-cells.org][Seeing ~(X . Y)~ at the end of a list]]

** C

This section is for all questions relating to C.

Before getting started with C you should [[file:c-ide-compiler.org][set up your development environment]].

*** FAQ

- [[file:c-booleans.org][Booleans in C]]

*** Exercises

- [[file:c-exercise-map-filter.org][Function pointers (map/filter)]]
- [[file:c-exercise-dictionary.org][Memory allocation (implementing a hashmap)]]

** COMMENT Ruby

This section is for all questions relating to Ruby.

** Contributing

If you have something you'd like to contribute to this website, be it an answer to a question you
want answered, you notice a typo, or anything else, feel free to make an issue or pull request on
the [[https://github.com/comp-348/comp-348.github.com][GitHub repository]].
